### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by findaz** [jiffyclub/snakeviz#145]
Downloaded snakeviz via conda for the first time and I followed instructions on the website to run it and got the following error. Any ideas?

C:\Users\joseph.findlay\Projects\SF6\sf6py>snakeviz um_core.1.loop.prof
Traceback (most recent call last):
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\Scripts\snakeviz-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\lib\site-packages\snakeviz\cli.py", line 123, in main
    app.listen(p, address=hostname)
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\lib\site-packages\tornado\web.py", line 2116, in listen
    server.listen(port, address)
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "C:\Users\joseph.findlay\AppData\Local\Continuum\Miniconda3\envs\sf6\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by jiffyclub** [comment]
This is the same as #138 and has been fixed in version 2.1.0. It looks like [conda](https://anaconda.org/anaconda/snakeviz) and [conda-forge](https://anaconda.org/conda-forge/snakeviz) are still supplying version 2.0.1, but hopefully that'll be updated soon. You may be able to install snakeviz via pip in the meantime to get the latest version.
