### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by ssbarnea** [jiffyclub/snakeviz#175]
I got this exception with the first profile I tried on Python 3.10 on MacOS (arm64).
```
$ snakeviz perf.prof 
snakeviz web server started on 127.0.0.1:8080; enter Ctrl-C to exit
http://127.0.0.1:8080/snakeviz/%2FUsers%2Fssbarnea%2Fc%2Fos%2Fzuul-jobs%2Fperf.prof
2022-04-28 18:27:37.537 osascript[98698:6850300] ApplePersistence=NO
ERROR:tornado.application:Uncaught exception GET /snakeviz/%2FUsers%2Fssbarnea%2Fc%2Fos%2Fzuul-jobs%2Fperf.prof (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:8080', method='GET', uri='/snakeviz/%2FUsers%2Fssbarnea%2Fc%2Fos%2Fzuul-jobs%2Fperf.prof', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/snakeviz/main.py", line 37, in get
    table_rows=table_rows(s), callees=json_stats(s))
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/snakeviz/stats.py", line 62, in json_stats
    nstats[nk]['children'] = dict(
  File "/Users/ssbarnea/.pyenv/versions/3.10.3/lib/python3.10/site-packages/snakeviz/stats.py", line 63, in <genexpr>
    (keyfmt(*ck), list(cv)) for ck, cv in v.items())
TypeError: 'int' object is not iterable
ERROR:tornado.access:500 GET /snakeviz/%2FUsers%2Fssbarnea%2Fc%2Fos%2Fzuul-jobs%2Fperf.prof (127.0.0.1) 49.62ms
```
The profile can be accessed at https://sbarnea.com/ss/perf.prof

**Comment by AWhetter** [comment]
I came across this problem when using a profile that was mistakenly generated with `python -m profile -o perf.prof ...`. If I use cProfile instead then the profile is displayed correctly by snakeviz.

It would be nice if snakeviz could exit more gracefully in this scenario, by detecting when a profile is generated like this and it guides the user to using cProfile instead.
