### ISSUE TITLE
Running snakeviz with Django

### ISSUE THREAD

**Issue by andybak** [jiffyclub/snakeviz#33]
I've had a go using runprofileserver: https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/runprofileserver.py

but I get:

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pstats.py", line 110, in load_stats
    self.stats = marshal.load(f)
ValueError: bad marshal data (unknown type code)

both with and without the --kcachegrind switch. I'm guessing that the output isn't in the right format but I don't know much about this topic so I'm hoping you can shed some light.

**Comment by BurkovBA** [comment]
Doesn't work for me. I say:

`python manage.py runprofileserver --prof-path ./prof --use-cprofile`

then visit the profiled page (its cprofile-formatted `.prof` file is generated)

After that run `snakeviz`:

`snakeviz sitemap-rna.xml.000080ms.1518091027.prof`, go to localhost:8080 and it says:

```python
Traceback (most recent call last):
  File "/Users/burkov/Documents/Projects/ebi/rnacentral-webcode/UENV/lib/python2.7/site-packages/tornado/web.py", line 1489, in _execute
    result = self.prepare()
  File "/Users/burkov/Documents/Projects/ebi/rnacentral-webcode/UENV/lib/python2.7/site-packages/tornado/web.py", line 2224, in prepare
    raise HTTPError(self._status_code)
HTTPError: HTTP 404: Not Found
```

I'm on MacOS 10.12.5, Django1.11, python2.7.

Thank you!
