### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by nav-agarwal** [jiffyclub/snakeviz#43]
I recently updated snakeviz from 0.1.4 to latest version using pip upgrade. The reason of upgrading it is that the chart was not getting displayed. Although the table with calls and other data was there. After reading this article (http://penandpants.com/2014/12/01/snakeviz-0-2/) , I thought it will work after upgrade. But after upgrade it even failed to show the table and gave following error:

```pytb
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\tornado\web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Python27\lib\site-packages\snakeviz\main.py", line 30, in get
    table_rows=table_rows(s), callees=json_stats(s))
  File "C:\Python27\lib\site-packages\snakeviz\stats.py", line 33, in table_rows
    tot_time_per = fmt(v[2] / v[0])
ZeroDivisionError: float division by zero
```

From the error, it looks that error handling for 'Division by zero' is missing.  
My Env:
Windows 7
Python2.7.8

I also tried running it on Python 3.4, but it also failed with following error:

```pytb
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\tornado\web.py", line 1332, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "C:\Python34\lib\site-packages\snakeviz\main.py", line 27, in get
    s = Stats(profile_name)
  File "C:\Python34\lib\pstats.py", line 69, in __init__
    self.init(arg)
  File "C:\Python34\lib\pstats.py", line 83, in init
    self.load_stats(arg)
  File "C:\Python34\lib\pstats.py", line 97, in load_stats
    self.stats = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

Note: I can't share cprofile output as it has customer data.

Thanks,
Naveen

**Comment by jiffyclub** [comment]
@nav-agarwal, could try installing from the [div-zero-error branch](https://github.com/jiffyclub/snakeviz/tree/div-zero-error) and see if that allows you to see your profile? An easy way to install that with pip is to run:

```
pip install -U https://github.com/jiffyclub/snakeviz/archive/div-zero-error.zip
```

Thanks!
